# basic config
alg: fedavg
suffix: dual_test/domainnet-32-Luni-Funi
resume_round: 0
device: [ 0,1,2,3 ]
test_device: [ 0 ] # only used in async FL test
dataset: domainnet-32-Luni-Funi
model: resnet18
model_in_cpu: false

# federated config
total_num: 32
sr: 0.125
rnd: 200
test_gap: 4

# local training config
bs: 64
epoch: 1
lr: 0.01
gamma: 0.99

