# basic config
alg: fedavg
suffix: reload_test
resume_round: 0
device: [ 0,1,2 ]
dataset: cifar10
model: resnet18
model_in_cpu: false

# federated config
total_num: 20
sr: 0.2
rnd: 100
test_gap: 4

# local training config
bs: 64
epoch: 1
lr: 0.01
gamma: 0.99

decay: 0.3
delay: 5
delay_rate: 0.3