# basic config
alg: fedavg
suffix: teest1
#resume_round: 3
device: 1
dataset: cifar10
model: resnet18
model_in_cpu: false

# federated config
total_num: 20
sr: 0.1
rnd: 5
test_gap: 1

# local training config
bs: 10
epoch: 5
lr: 0.01
gamma: 0.99

decay: 0.3
delay: 5
delay_rate: 0.3